package io.akka.sbt.mimabom

import java.io.File

import com.typesafe.tools.mima.core.ProblemFilter
import com.typesafe.tools.mima.core.util.log.Logging
import com.typesafe.tools.mima.lib.MiMaLib

import sbt._
import sbt.Keys._
import sbt.librarymanagement.DependencyResolution
import sbt.librarymanagement.ivy.IvyDependencyResolution

final case class ModuleCheck(
    key: String,
    oldVersion: String,
    newVersion: String,
    problems: List[String],
    skippedReason: Option[String])

final case class BomCompatReport(
    removed: Seq[BomEntry],
    disallowedRemovals: Seq[BomEntry],
    added: Seq[BomEntry],
    unchangedCount: Int,
    checks: Seq[ModuleCheck]) {
  def incompatible: Seq[ModuleCheck] = checks.filter(_.problems.nonEmpty)
  def skipped: Seq[ModuleCheck] = checks.filter(_.skippedReason.nonEmpty)
  def hasErrors: Boolean = disallowedRemovals.nonEmpty || incompatible.nonEmpty
}

object MimaBomPlugin extends AutoPlugin {
  override def trigger = noTrigger

  object autoImport {
    val bomCompatPreviousArtifact = settingKey[Option[ModuleID]](
      "Coordinates of the previously released BOM to compare against, e.g. Some(\"io.akka\" % \"akka-runtime-dependencies\" % \"1.0.0\").")
    val bomCompatPreviousFile = settingKey[Option[File]](
      "Local pom.xml to compare against; takes precedence over bomCompatPreviousArtifact.")
    val bomCompatCurrentFile = settingKey[File](
      "pom.xml describing the current BOM (e.g. the file generated by sbt-artifact-bom).")
    val bomCompatAllowedRemovals = settingKey[Set[String]](
      "\"org:name\" entries that are allowed to disappear from the BOM.")
    val bomCompatIgnoredModules = settingKey[Set[String]](
      "\"org:name\" entries excluded from binary-compatibility analysis (still checked for presence).")
    val bomCompatProblemFilters = settingKey[Seq[ProblemFilter]](
      "MiMa problem filters applied to every module, e.g. ProblemFilters.exclude[Problem](\"com.example.internal.*\").")
    val bomCompatModuleProblemFilters = settingKey[Map[String, Seq[ProblemFilter]]](
      "MiMa problem filters applied to a single \"org:name\" module.")
    val bomCompatExcludeAnnotations = settingKey[Seq[String]](
      "Fully-qualified annotation names whose carriers are excluded from checking, e.g. akka.annotation.ApiMayChange.")
    val bomCompatReport = taskKey[BomCompatReport](
      "Diffs the previous BOM against the current one and runs MiMa on every entry whose version changed.")
    val bomCompat = taskKey[Unit](
      "Fails the build if the BOM dropped entries or changed an entry to a binary-incompatible version.")
  }
  import autoImport._

  override lazy val projectSettings: Seq[Setting[_]] = Seq(
    bomCompatPreviousArtifact := None,
    bomCompatPreviousFile := None,
    bomCompatCurrentFile := baseDirectory.value / "pom.xml",
    bomCompatAllowedRemovals := Set.empty,
    bomCompatIgnoredModules := Set.empty,
    bomCompatProblemFilters := Nil,
    bomCompatModuleProblemFilters := Map.empty,
    bomCompatExcludeAnnotations := Nil,
    bomCompatReport := bomCompatReportTask.value,
    bomCompat := bomCompatTask.value)

  private def bomCompatReportTask = Def.task {
    val log = streams.value.log
    val lm = dependencyResolution.value
    val ivyConf = ivyConfiguration.value
    val workDir = target.value / "mima-bom"
    IO.createDirectory(workDir)

    val previousPom: File = bomCompatPreviousFile.value match {
      case Some(f) =>
        if (!f.exists) sys.error(s"bomCompatPreviousFile does not exist: $f")
        f
      case None =>
        val module = bomCompatPreviousArtifact.value.getOrElse(sys.error(
          "Set bomCompatPreviousArtifact := Some(\"org\" % \"bom-name\" % \"x.y.z\") " +
            "(or bomCompatPreviousFile) to define the baseline BOM."))
        fetchPom(IvyDependencyResolution(ivyConf), module, workDir / "previous-bom", log)
    }
    val currentPom = bomCompatCurrentFile.value
    if (!currentPom.exists) sys.error(s"bomCompatCurrentFile does not exist: $currentPom")

    val oldEntries = dedupe(PomParser.parse(previousPom))
    val newEntries = dedupe(PomParser.parse(currentPom))
    log.info(s"mima-bom: previous BOM has ${oldEntries.size} entries, current has ${newEntries.size}")

    val newById = newEntries.map(e => e.id -> e).toMap
    val oldById = oldEntries.map(e => e.id -> e).toMap

    val removed = oldEntries.filterNot(e => newById.contains(e.id))
    val allowedRemovals = bomCompatAllowedRemovals.value
    val disallowedRemovals = removed.filterNot(e => allowedRemovals.contains(e.key))
    val added = newEntries.filterNot(e => oldById.contains(e.id))
    val changed = oldEntries.flatMap(old => newById.get(old.id).filter(_.version != old.version).map(old -> _))
    val unchangedCount = oldEntries.count(old => newById.get(old.id).exists(_.version == old.version))

    val ignored = bomCompatIgnoredModules.value
    val globalFilters = bomCompatProblemFilters.value
    val moduleFilters = bomCompatModuleProblemFilters.value
    val excludeAnnots = bomCompatExcludeAnnotations.value.toList

    // Resolve the jars of all current entries once: they double as MiMa's context classpath,
    // so superclasses defined in other BOM entries resolve during analysis.
    val jarDir = workDir / "jars"
    val checkable = newEntries.filter(e => e.classifier.isEmpty && (e.tpe == "jar" || e.tpe.isEmpty))
    log.info(s"mima-bom: resolving ${checkable.size} current jars (context classpath) ...")
    val currentJars: Map[String, File] = checkable.flatMap { e =>
      fetchJar(lm, e, jarDir, log) match {
        case Right(jar) => Some(e.key -> jar)
        case Left(err) =>
          log.warn(s"mima-bom: could not resolve current jar for $e: $err")
          None
      }
    }.toMap
    val contextCp = currentJars.values.toSeq

    val mimaLogging: Logging = new SbtMimaLogging(log)

    val checks: Seq[ModuleCheck] = changed.map { case (old, nu) =>
      def skip(reason: String) = ModuleCheck(old.key, old.version, nu.version, Nil, Some(reason))
      if (ignored.contains(old.key)) skip("listed in bomCompatIgnoredModules")
      else if (old.classifier.nonEmpty) skip(s"classifier artifact (${old.classifier.get})")
      else if (old.tpe != "jar" && old.tpe.nonEmpty) skip(s"type '${old.tpe}'")
      else
        currentJars.get(old.key) match {
          case None => skip("current jar could not be resolved")
          case Some(newJar) =>
            fetchJar(lm, old, jarDir, log) match {
              case Left(err) => skip(s"previous jar could not be resolved: $err")
              case Right(oldJar) =>
                log.info(s"mima-bom: checking ${old.key} ${old.version} -> ${nu.version}")
                val filters = globalFilters ++ moduleFilters.getOrElse(old.key, Nil)
                val problems = new MiMaLib(contextCp, mimaLogging)
                  .collectProblems(oldJar, newJar, excludeAnnots)
                  .filter(p => filters.forall(f => f(p)))
                ModuleCheck(old.key, old.version, nu.version, problems.map(_.description("current")), None)
            }
        }
    }

    BomCompatReport(removed, disallowedRemovals, added, unchangedCount, checks)
  }

  private def bomCompatTask = Def.task {
    val report = bomCompatReport.value
    val log = streams.value.log

    if (report.added.nonEmpty)
      log.info(s"mima-bom: ${report.added.size} entries added: ${report.added.mkString(", ")}")
    report.removed.foreach { e =>
      if (report.disallowedRemovals.contains(e))
        log.error(s"mima-bom: entry removed from BOM: $e")
      else
        log.info(s"mima-bom: entry removed from BOM (allowed): $e")
    }
    report.skipped.foreach { c =>
      log.warn(s"mima-bom: skipped ${c.key} ${c.oldVersion} -> ${c.newVersion}: ${c.skippedReason.get}")
    }
    report.checks.filter(c => c.skippedReason.isEmpty && c.problems.isEmpty).foreach { c =>
      log.info(s"mima-bom: ${c.key} ${c.oldVersion} -> ${c.newVersion}: binary compatible")
    }
    report.incompatible.foreach { c =>
      log.error(s"mima-bom: ${c.key} ${c.oldVersion} -> ${c.newVersion}: ${c.problems.size} binary incompatibilities")
      c.problems.foreach(p => log.error(s"  * $p"))
    }

    if (report.hasErrors) {
      val parts =
        (if (report.disallowedRemovals.nonEmpty) List(s"${report.disallowedRemovals.size} entries removed") else Nil) ++
          (if (report.incompatible.nonEmpty) List(s"${report.incompatible.size} binary-incompatible upgrades") else Nil)
      throw new MessageOnlyException(s"mima-bom check failed: ${parts.mkString(", ")}")
    } else {
      log.info(s"mima-bom: OK (${report.unchangedCount} unchanged, ${report.checks.size} version changes checked, " +
        s"${report.added.size} added, ${report.removed.size} removed/allowed)")
    }
  }

  // BOMs occasionally list the same artifact more than once (e.g. with classifiers); keep the first of each id.
  private def dedupe(entries: Seq[BomEntry]): Seq[BomEntry] = {
    val seen = collection.mutable.Set[(String, String, Option[String])]()
    entries.filter(e => seen.add(e.id))
  }

  private def fetchPom(lm: DependencyResolution, module: ModuleID, dir: File, log: Logger): File = {
    val pomModule = module.intransitive().withExplicitArtifacts(Vector(Artifact(module.name, "pom", "pom")))
    lm.retrieve(pomModule, scalaModuleInfo = None, dir, log) match {
      case Right(files) =>
        files
          .find(f => f.getName.endsWith(".pom") || f.getName.endsWith(".xml"))
          .getOrElse(sys.error(s"Resolved $module but no pom found among: ${files.mkString(", ")}"))
      case Left(w) => throw w.resolveException
    }
  }

  private def fetchJar(lm: DependencyResolution, entry: BomEntry, dir: File, log: Logger): Either[String, File] = {
    val module = (entry.organization % entry.name % entry.version).intransitive()
    lm.retrieve(module, scalaModuleInfo = None, dir, log) match {
      case Right(files) =>
        files.find(_.getName == s"${entry.name}-${entry.version}.jar")
          .orElse(files.find(_.getName.endsWith(".jar")))
          .toRight(s"resolved but no jar among: ${files.mkString(", ")}")
      case Left(w) => Left(w.resolveException.getMessage)
    }
  }

  private final class SbtMimaLogging(log: Logger) extends Logging {
    override def verbose(str: String): Unit = log.verbose(str)
    override def debug(str: String): Unit = log.debug(str)
    override def warn(str: String): Unit = log.warn(str)
    override def error(str: String): Unit = log.error(str)
  }
}
